baseURL = 'https://baka-op.github.io'
languageCode = 'en-us'
title = 'Baka'
theme = 'PaperMod'
enableEmoji = true

[params]
ShowShareButtons = true
ShareButtons = [ "linkedin", "twitter", "reddit"]

[params.homeInfoParams]
Title = "Baka"
Content = "Hey there! I'm Baka, a 16 y.o. highschool student and computer science enthusiast. My hobbies encapsulate writing, music, games and their development, script/tool/mod creation."

[[params.socialIcons]]
name = "itchio"
url = "https://bakaop.itch.io"

[[params.socialIcons]]
name = "github"
url = "https://www.github.com/Baka-OP/"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@_bakaa_"

[[params.socialIcons]]
name = "discord"
url = "https://discord.com/invite/WseNACbmQx"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/da_real_baka"

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]

